### PR TITLE
[FIXED] Honor max_connections setting

### LINKED ISSUE #386: max_connection is not honored
The max_connections setting is getting loaded (reported by /varz), but its limit is not enforced.
I made a test case here: <https://github.com/nats-io/gnatsd/tree/max_connection_test>

### PR DESCRIPTION
**Pull request by kozlovic**
The max_connections config parameter was accepted but the server
would not check this limit when processing client connections.

Resolves #386

### CODE REVIEW

**Comment by kozlovic** [comment]
@derekcollison Did not see that you assigned #386 to yourself. Feel free to ignore this PR. Not even sure if this is the best way of enforcing the limit.

File: server/client.go [hunk 1]
```diff
@@ -447,6 +447,12 @@ func (c *client) processConnect(arg []byte) error {
 			srv.mu.Unlock()
 		}
 
+		// Check for max connections
```
Comment (derekcollison) [inline server/client.go]: The client does not technically have to send a connect (think telnet to demo server). So we should probably check on accept and simply send an error there.

File: server/client.go [hunk 2]
```diff
@@ -490,6 +496,18 @@ func (c *client) authViolation() {
 	c.closeConnection()
 }
 
+func (c *client) maxConnLimit() {
+	if c.srv != nil && c.srv.opts.Users != nil {
```
Comment (derekcollison) [inline server/client.go]: Since its global scope I think we can just use the non-user generic one below, don't need the user specific one IMO.

File: server/errors.go [hunk 3]
```diff
@@ -25,4 +25,8 @@ var (
 
 	// ErrBadClientProtocol signals a client requested an invalud client protocol.
 	ErrBadClientProtocol = errors.New("Invalid Client Protocol")
+
+	// ErrTooManyConnections signals a client that the maximum number of connections supported by the
+	// server has been reached.
+	ErrTooManyConnections = errors.New("Too many connections")
```
Comment (derekcollison) [inline server/errors.go]: Maybe "Maximum Connections Exceeded"

File: server/server.go [hunk 4]
```diff
@@ -731,6 +731,17 @@ func (s *Server) checkAuth(c *client) bool {
 	}
 }
 
+// Check that number of clients is below Max connection setting.
+func (s *Server) checkMaxConn(c *client) bool {
+	if c.typ == CLIENT {
```
Comment (derekcollison) [inline server/server.go]: If we have added to s.clients, we could just do the following since if its a route will be ok I think.

s.mu.Lock()
defer s.mu.Unlock()
return len(s.clients) <+ s.opts.MaxConn

File: server/server_test.go [hunk 5]
```diff
@@ -223,3 +226,25 @@ func TestNoDeadlockOnStartFailure(t *testing.T) {
...
+	nc, err := nats.Connect(addr)
+	if err != nil {
+		t.Fatalf("Error creating client: %v\n", err)
+	}
+	defer nc.Close()
+
+	nc2, err := nats.Connect(addr)
+	if err == nil {
+		if nc2 != nil {
+			nc2.Close()
```
Comment (derekcollison) [inline server/server_test.go]: We can call Close() on nil no?

**Comment by derekcollison** [comment]
Thanks for the PR @kozlovic, no worries.

File: server/server_test.go (hunk 5 above)
Comment (kozlovic) [inline server/server_test.go]: No we can't, but I should not check for `nc2 != nil` since if `err == nil`, it means that `nc2` is not nil!

File: server/server.go (hunk 4 above)
Comment (kozlovic) [inline server/server.go]: And there is a huge defect here that I should check that s.opts.MaxConn is > 0 first!!!

File: server/errors.go (hunk 3 above)
Comment (kozlovic) [inline server/errors.go]: Ok

File: server/client.go (hunk 2 above)
Comment (kozlovic) [inline server/client.go]: Ok

File: server/client.go (hunk 1 above)
Comment (kozlovic) [inline server/client.go]: This is what I did first (hence the fix in `clearConnection` because when calling `closeConnection` before client is initialized would crash since `c.bw` was `nil`).
Keep in mind that the client expects an INFO before any possible error message. So I need to do the send after the client is initialized (buffer created so that sendErr actually works) and after sending the server info, all that in `createClient()`. The problem with this approach is that the client will get the error only, in my tests, 10% of the cases. Otherwise, it either gets `EOF` or `connection reset by peer`. With the original approach, it gets the error 100% of the times. That being said, I understand the argument of telnet, etc.. so I guess it is worth having the client not always know why it failed to connect but maximizing the protection of the server, right?

**Comment by kozlovic** [comment]
@derekcollison I just realized that probably [this check](https://github.com/nats-io/gnatsd/pull/387/files#diff-853eb184ac73cf9597d7833f6b89e9c9R273) is no longer relevant since we close the client connection before starting the client's `readLoop`.

**Comment by derekcollison** [comment]
Feel free to remove in new PR.
