### PR TITLE
Fixes to remove traced password

### LINKED ISSUE #762: Password obfuscation in trace does not work properly
If username and password are the same, or simply if the password text is present in the trace before actual location of the password, that string would be replaced.
For instance, trying to connect with URL `nats://ivan:ivan@localhost:4222` would produce this trace:
```
[TRC] ::1:49797 - cid:1 - ->> [CONNECT {"verbose":false,"pedantic":false,"user":"[REDACTED]","pass":"ivan","tls_required":false,"name":"","lang":"go","version":"1.6.1","pr
```

### PR DESCRIPTION
**Pull request by wallyqs**
Alternate approach to fix https://github.com/nats-io/gnatsd/issues/762 and https://github.com/nats-io/gnatsd/pull/766 continuing to use regex based approach to filter password entries from the log instead of using JSON.

Signed-off-by: Waldemar Quevedo <wally@synadia.com>

 - [x] Resolves #762 
 - [x] Documentation added (if applicable)
 - [x] Tests added
 - [x] Branch rebased on top of current master (`git pull --rebase origin master`)
 - [x] Changes squashed to a single commit (described [here](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
 - [x] Build is green in Travis CI
 - [x] You have certified that the contribution is your original work and that you license the work to the project under the [Apache 2 license](https://github.com/nats-io/gnatsd/blob/master/LICENSE)

Resolves #762 

/cc @nats-io/core

### CODE REVIEW

File: server/client.go [hunk 1]
```diff
@@ -756,28 +756,36 @@ func (c *client) processErr(errStr string) {
...
+// messages for logging.
 func removePassFromTrace(arg []byte) []byte {
-
-	if !bytes.Contains(arg, []byte("pass")) {
+	if !bytes.Contains(arg, []byte(`pass`)) {
 		return arg
 	}
-	m := passPat.FindAllSubmatch(arg, -1)
+	// Take a copy of the connect proto just for the trace message.
+	a := make([]byte, len(arg))
```
Comment (derekcollison) [inline server/client.go]: Maybe place on the stack since it probably does not escape? Compiler may do this for you these days.

I used to do
```
var _raw [4096]byte
buf := _raw[:0]
buf = append(buf, ...)
```

Comment (wallyqs) [reply server/client.go]: Thanks, updated to take this approach.

File: server/client.go [hunk 2]
```diff
@@ -756,28 +756,37 @@ func (c *client) processErr(errStr string) {
...
-
-	if !bytes.Contains(arg, []byte("pass")) {
+	if !bytes.Contains(arg, []byte(`pass`)) {
 		return arg
 	}
-	m := passPat.FindAllSubmatch(arg, -1)
+	// Take a copy of the connect proto just for the trace message.
+	var _arg [4096]byte
+	buf := _arg[:0]
+	buf = append(buf, arg...)
```
Comment (derekcollison) [inline server/client.go]: Can be `buf := append(_arg[:0], arg...)`

Comment (wallyqs) [reply server/client.go]: ok just updated again, thanks for the tip

**Comment by derekcollison** [comment]
LGTM
