### PR TITLE
Fix possible authentication timeout after accepting CONNECT proto

### LINKED ISSUE #289: Server can send "authorization timeout" to client after accepting its CONNECT
In some race conditions, I believe that it is possible for the server to still send an authorization timeout (and close the connection) to a client after accepting its `CONNECT` protocol and responding to a `PING`. The issue is that then the client receives this error through its readLoop (not during the connect/reconnect handshake) which causes the client library to close the connection, preventing any reconnect.

I believe that the server should check the returned boolean from `c.atmr.Stop()` which, if `false`, would indicate that the timer could not be stopped, likely because the routine has been started/is executing. In this case, the server should return the auth timeout error in place and close the connection to prevent the client from receiving `PONG` and start its readLoop.

### PR DESCRIPTION
**Pull request by kozlovic**
This PR addresses the issue by testing the result of the
`Timer.Stop()` method, which if `false` indicates that the callback
may be in progress. When that happens, the `processConnect` method
will wait for the callback to finish and simply return. The auth
timeout error will therefore be received by the client during the
synchronous connect process, which will allow it to try again.

Resolves #289

### CODE REVIEW

File: server/client.go [hunk 1]
```diff
@@ -310,10 +310,19 @@ func (c *client) processErr(errStr string) {
...
 
-	// This will be resolved regardless before we exit this func,
-	// so we can just clear it here.
 	c.mu.Lock()
-	c.clearAuthTimer()
+	// If we can't stop the timer because the callback is in progress...
+	if !c.clearAuthTimer() {
+		// wait for it to finish and handle sending the failure back to
+		// the client.
+		for c.nc != nil {
```
Comment (kozlovic) [inline server/client.go]: I would rather wait on some kind of waitgroup here, but I think that we start to be conservative with what we add in the client structure.
This situation (unable to stop the timer because in progress) is pretty rare: I have not been able to reproduce with a test case (without changing the code to sleep in proper places). So that simple approach without added object may be ok.

**Comment by ColinSullivan1** [comment]
LGTM.  I was not able to reproduce this either, but indirectly verified this case by handling this situation with fix to the .NET client.  A user was stress testing a heavily loaded windows VM with hundreds of clients simultaneously connecting.
