### PR TITLE
[FIXED] Authorization Timeout and TLS

### LINKED ISSUE #432: Authorization Timeout and TLS
When TLS and authorization is enabled, the authorization timeout can fire during the TLS handshake, causing the server to write the authorization timeout error string into the client socket, injecting what becomes bad data into the TLS handshake.  This creates misleading errors on the client such as `tls: oversized record received with length 21024`.

I've only seen this happen when the host machine is under very heavy load with many clients simultaneously connecting, causing the server to become CPU bound.

There are a few ways to tackle this, but I propose waiting to schedule the authorization timer until after TLS is fully established to avoid this scenario.  Any thoughts?

### PR DESCRIPTION
**Pull request by tylertreat**
When TLS and authorization is enabled, the authorization timeout can
fire during the TLS handshake, causing the server to write the
authorization timeout error string into the client socket, injecting
what becomes bad data into the TLS handshake. This creates misleading
errors on the client such as tls: oversized record received with length
21024.

 - [x] Link to issue, e.g. `Resolves #NNN`
 - [x] Documentation added (if applicable)
 - [x] Tests added
 - [x] Branch rebased on top of current master (`git pull --rebase origin master`)
 - [x] Changes squashed to a single commit (described [here](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
 - [x] Build is green in Travis CI
 - [x] You have certified that the contribution is your original work and that you license the work to the project under the [MIT license](https://github.com/nats-io/gnatsd/blob/master/LICENSE)

Resolves #432

### Changes proposed in this pull request: 

This moves the authorization timeout scheduling to after the TLS
handshake to avoid the race. This should be safe since TLS has its own
handshake timeout. Added a unit test that fails with the old behavior
and passes with the new. LMK if you can think of a better way to test
this.
 
/cc @nats-io/core

### CODE REVIEW

File: server/server.go [hunk 1]
```diff
@@ -608,6 +603,13 @@ func (s *Server) createClient(conn net.Conn) *client {
 		c.mu.Lock()
 	}
 
+	// Check for Auth. We schedule this timer after the TLS handshake to avoid
+	// the race where the timer fires during the handshake and causes the
+	// server to write bad data to the socket. See issue #432.
+	if authRequired {
```
Comment (kozlovic) [inline server/server.go]: You could move this after the check for `c.nc == nil` since connection may have been closed while lock was released in TLS case above.

**Comment by kozlovic** [comment]
LGTM after moving the test.

**Comment by ColinSullivan1** [comment]
LGTM.

**Comment by tylertreat** [comment]
@kozlovic moving what test?

**Comment by kozlovic** [comment]
@tylertreat Sorry for my broken english ;-) I saw that you updated based on my comments and did a push force. So I was saying LGTM since you have moved the code after the `nc == nil` check.
